### ISSUE TITLE
PGAFitness: Overflow computing cmax fitness

### ISSUE THREAD

**Issue by wj314** [schlatterbeck/pgapack#7] opened 2022-12-03 07:00 UTC
Hi，
I get a Fatal error and the following information appears:
PGAFitness: Overflow computing cmax fitness
Values: cmax=1.077688e+22, evalue=7.186031e+04
You can use a ranking variant of fitness computation

I see the PGAPACK code in fitnesss.c and found:
        if (cmax == cmax - evalue && evalue != 0) {

            PGAErrorPrintf (ctx, PGA_FATAL
                , "PGAFitness: Overflow computing cmax fitness\n"
                  "Values: cmax=%e, evalue=%e\n"
                  "You can use a ranking variant of fitness computation\n"
                , cmax, evalue
                );
        }

But the cmax value 1.077688e+22 is lower than the max double value 1.797693e+308. I don't know the reason for this "Overflow".
By the further test about "cmax == cmax - evalue", I found the condition is indeed true when cmax=1.077688e+22 and evalue=10000.
I'm confused about the problem. Could you give a reason? Maybe It is a common sense about C++ or the computer system but I don't know.

**Comment by schlatterbeck** [comment] 2022-12-03 08:40
On Fri, Dec 02, 2022 at 11:00:55PM -0800, wj314 wrote:
> Hi，
> I get a Fatal error and the following information appears:
> PGAFitness: Overflow computing cmax fitness
> Values: cmax=1.077688e+22, evalue=7.186031e+04
> You can use a ranking variant of fitness computation

That overflow happens when cmax i large compared to the current
evaluation value evalue. As you can see from the comparison:

>         if (cmax == cmax - evalue && evalue != 0) {

this happens when subtracting the evalue from the current cmax value
does not change cmax. So evalue is so small compared to cmax that the
double data type cannot represent the difference.

> But the cmax value 1.077688e+22 is lower than the max double value
> 1.797693e+308. I don't know the reason for this "Overflow".

Maybe overflow is the wrong word here in the error message, let me know
what you'd put in the error message there.

> By the further test about "cmax == cmax - evalue", I found the
> condition is indeed true when cmax=1.077688e+22 and evalue=10000.

Yes. Because 10000 is so small compared to 1e22 that adding/subtracting
it won't change the larger value.

> I'm confused about the problem. Could you give a reason? Maybe It is a
> common sense about C++ or the computer system but I don't know.

The reason is that in a floating point (or double) representation you
have a certain size of the mantissa (the significant digits). The
mantissa is kept separately from the exponent. Now when you add a very
large number and comparatively small number the result cannot be
represented by the limited mantissa of the large number.

That all said: The fitness normalization is not used for selection
schemes that do comparisons directly. You may want to use 
PGA_SELECT_TOURNAMENT or PGA_SELECT_TRUNCATION with PGASetSelectType.
(If you're using the latter be sure to upgrade to 2.2.1 which I've
pushed yesterday, this has a fix for truncation selection).  
This avoids the problem.

Note that the selection schemes that need a separate fitness computation
like proportional selection (aka roulette wheel selection) have other
problems, too, proportional selection has too much selection pressure in
the beginning and too low at the end.
https://en.wikipedia.org/wiki/Fitness_proportionate_selection
You may want to read [1] why proportional selection is typically not a
good idea (it was historically the first selection scheme and is
described in Goldberg's book [2] which is probably the reason it is
still being used). Note that there is an earlier report from Blickle and
Thiele [3] that is more frank about the use of proportional selection:
"All the undesired properties together led us to the conclusion that
proportional selection is a very unsuited selection scheme. Informally
one can say that the only advantage of proportional selection is that it
is so difficult to prove the disadvantages" [3, p. 42] they were not as
outspoken in the final paper :-)

You're seeing this yourself: You have very high differences between good
and bad evaluation (in fact so large that the fitness cannot be
computed, see above). So when using proportional selection the very good
individuals will be selected with too high probability resulting in
premature convergence.

That all said: If you're doing optimization with genes of type 'real',
you may want to try Differential Evolution [4], [5], [6]. At least in my
experiments with antenna optimization [7] the results outperform the
standard genetic algorithm, but this is reported by several
practitioners. Examples of how to use this are in
examples/deb/optimize.c or examples/mgh/testprogde.c
The PGASetDECrossoverProb is critical, for problems where the dimensions
cannot typically be optimized separately the value should be set close
to 1 but not equal to 1.

If want to read some of the articles I've cited and cannot find them,
feel free to drop me an email and I can send them to you.

[1] Blickle, Tobias; Thiele, Lothar (1996). "A Comparison of Selection
    Schemes Used in Evolutionary Algorithms". Evolutionary Computation.
    4 (4): 361–394.
    https://dl.acm.org/doi/pdf/10.1162/evco.1996.4.4.361
[2] David E. Goldberg. Genetic Algorithms in Search, Optimization &
    Machine Learning. Addison Wesley, October 1989.
[3] Tobias Blickle and Lothar Thiele. A comparison of selection
    schemes used in genetic algorithms. TIK-Report 11 Version 2,
    Computer Engineering and Communications Lab (TIK), December 1995.
    https://tik-old.ee.ethz.ch/file/6c0e384dceb283cd4301339a895b72b8/TIK-Report11.pdf
[4] Rainer Storn and Kenneth Price. Differential evolution – a simple
    and efficient heuristic for global optimization over continuous
    spaces. Journal of Global Optimization, 11(4):341–359, December 1997.
[5] Rainer Storn and Kenneth Price. Differential evolution – a simple
    and efficient adaptive scheme for global optimization over
    continuous spaces. Technical Report TR-95-012, International
    Computer Science Institute (ICSI), March 1995.
    ftp://ftp.icsi.berkeley.edu/pub/techreports/1995/tr-95-012.pdf
[6] Kenneth V. Price, Rainer M. Storn, and Jouni A. Lampinen.
    Differential Evolution: A Practical Approach to Global Optimization.
    Springer, Berlin, Heidelberg, 2005.
[7] Ralf Schlatterbeck. Multi-objective antenna optimization. Blog post,
    Open Source Consulting, December 2021.
    https://blog.runtux.com/posts/2021/12/27/

Ralf
-- 
Dr. Ralf Schlatterbeck                  Tel:   +43/2243/26465-16
Open Source Consulting                  www:   www.runtux.com
Reichergasse 131, A-3411 Weidling       email: ***@***.***

**Comment by schlatterbeck** [comment] 2022-12-04 11:47
I've issued a blog post, with a little more explanations:
https://blog.runtux.com/posts/2022/12/03/

Ralf

**Comment by schlatterbeck** [comment] 2023-10-08 19:25
Closing, not a bug.

**Comment by schlatterbeck** [comment] 2023-10-08 19:26
Closing, not a bug.

**Closed as completed by schlatterbeck** 2023-10-08 19:26 UTC
