### ISSUE TITLE
Parallel Problem

### ISSUE THREAD

**Issue by wj314** [schlatterbeck/pgapack#4] opened 2022-10-15 02:57 UTC
Hello,
When I write evaluate function in MPI program:
double evaluate (PGAContext *ctx, int p, int pop, double *aux)
{
    int i;
    int dimension = PGAGetStringLength (ctx);
    double e = 0;
    for (i=0; i<dimension; i++) {
        double x = PGAGetRealAllele (ctx, p, pop, i);
        e += x * x;
    }
    cout<<"rank= "<<PGAGetRank(ctx,MPI_COMM_WORLD)<<" "<<p<<" "<<pop<<" min "<<endl;
    return e;
}

I find that p value is always -1138 when I use more than 3 cpus. Only when I use 1 cpu, p value is between 0 and popsize-1. Can someone gives a reason? How to make p value in 0-(popsize-1) when using more than 3 cpus?

**Comment by schlatterbeck** [comment] 2022-10-15 08:13
When using MPI, the Individual is transferred to the remote MPI process. The remote MPI process receives this into the (fixed) individual PGA_TEMP1, performs the evaluation and sends the result back. See pgapack.h for PGA_TEMP1 (and PGA_TEMP2) which are defined as constants, in particular PGA_TEMP1 is defined as -1138. So there is nothing wrong with what you're observing.

**Closed as completed by schlatterbeck** 2022-10-15 08:13 UTC

**Comment by schlatterbeck** [comment] 2022-10-15 08:34
Update: For more questions you can email me directly at rsc@runtux.com.

**Comment by wj314** [comment] 2022-10-15 13:49
Thanks for your reply. But Could I get original p values in evaluate function by calling some functions?

**Comment by wj314** [comment] 2022-10-15 13:51
Thanks for your reply. But Could I get original p values in evaluate function by calling some functions?

**Comment by wj314** [comment] 2022-10-15 14:09
Dear schlatterbeck,
I have attempted to get original p values in evaluate function by modifying PGAEvaluateSlave and PGAEvaluateMS (See attachment).
But when I run my program in folder ./test2 by the command line "mpirun -np 3 ./a.out", the program blocks after printing two lines:
0
1.
I compiled the program with intel2018_mpi.
Could you give me some advice?
Jie Wang
2022.10.15
[pgapack_modify.tar.gz](https://github.com/schlatterbeck/pgapack/files/9792255/pgapack_modify.tar.gz)

**Comment by schlatterbeck** [comment] 2022-10-15 14:55
See my comments via email, we should continue the discussion via email, it's not a bug of pgapack.
