### ISSUE TITLE
update fitness value of an individual

### ISSUE THREAD

**Issue by fdmartins** [schlatterbeck/pgapack#3] opened 2022-04-12 23:24 UTC
Hello,

I'm using pgapack to optimize a non-deterministic function (eg reinforcement learning). By any chance, a given solution generates a good fitness, but not the best global fitness, how can I recalculate and update the individual value? Is setting PGASetPopSize and GASetNumReplaceValue to the same value the best alternative?

thank you!

**Comment by schlatterbeck** [comment] 2022-06-10 12:00
I'm not sure what you want to achieve.
By default the evaluation of an individual (if it doesn't change) stays the same. If you don't want this and want individuals to be re-evaluated each generation (even if they have not changed) you can use PGASetEvaluationUpToDateFlag to set the flag to PGA_FALSE to force re-evaluation.
If you set PGASetPopSize and GASetNumReplaceValue to the same value, *all* individuals are replaced in each generation. This is a non-elitist strategy and may not be what you want (it may happen that the best individual so far is lost)

**Comment by schlatterbeck** [comment] 2022-10-11 06:57
Hi Fabio,

On Tue, Apr 12, 2022 at 11:24:44PM +0000, Fabio wrote:
> Hello,
> 
> I'm using pgapack to optimize a non-deterministic function (eg
> reinforcement learning). By any chance, a given solution generates a
> good fitness, but not the best global fitness, how can I recalculate
> and update the individual value?

Hmm, I really don't understand what you want to achieve.

Do you want to enforce that the fitness is re-calculated for all
individuals?

> Is setting PGASetPopSize and
> GASetNumReplaceValue to the same value the best alternative?

This will replace *all* individuals in every generation. Depending on
what algorithms you have selected (which in turn depend on the type of
gene you're using, floating point, integer or boolean).

When using floating point, Differential Evolution is probably the way to
go and for this you *want* to replace the whole population depending on
the population replacement chosen.

So I need to know a little more about your application to help.

Best,
Ralf
-- 
Dr. Ralf Schlatterbeck                  Tel:   +43/2243/26465-16
Open Source Consulting                  www:   www.runtux.com
Reichergasse 131, A-3411 Weidling       email: ***@***.***

**Comment by schlatterbeck** [comment] 2022-10-15 14:53
No answer for quite some time, not a bug, closing.

**Closed as completed** 2022-10-15 14:53 UTC
